# Change these first
owner: hiveon
repo: status

sites:
  - name: hiveon.net Website
    url: https://hiveon.net
  - name: FCR
    url: https://status-proxy.o11y.hiveon.net/status/fcr
  - name: Automation
    url: https://status-proxy.o11y.hiveon.net/status/automation
  - name: Pool
    url: https://status-proxy.o11y.hiveon.net/status/pool
  - name: Warehouse
    url: https://status-proxy.o11y.hiveon.net/status/warehouse
  - name: Hiveon OS
    url: https://status-proxy.o11y.hiveon.net/status/hiveon_os
  - name: Machine OS
    url: https://status-proxy.o11y.hiveon.net/status/machine_os
  - name: IDP
    url: https://status-proxy.o11y.hiveon.net/status/idp
  - name: Analytics
    url: https://status-proxy.o11y.hiveon.net/status/analytics
  - name: Reports
    url: https://status-proxy.o11y.hiveon.net/status/reports
  - name: Energy Price Control
    url: https://status-proxy.o11y.hiveon.net/status/energy_price_control

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.hiveon.net
  publish: true
  # baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/the3line/upptime2/master/assets/HiveonLogo.svg
  name: Upptime
  introMessage: Status page for the Hiveon services
  navbar:
    - title: Status
      href: /status
    - title: hiveon.com
      href: https://hiveon.com

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

i18n:
  footer: Hiveon 
