# Change these first
owner: hiveon
repo: status

sites:
  - name: Hiveos Farm
    url: https://the.hiveos.farm
  - name: Hiveos Farm API
    url: https://api2.hiveos.farm/api/v2/healthcheck
    __dangerous__body_down: 'not ok'
    assignees:
      - the3line
  - name: hiveon.net site
    url: https://hiveon.net
  - name: hiveon.com site
    url: https://hiveon.com
  - name: Pool Health
    url: https://hiveon.net/api/v1/pool/health
  - name: btc.hiveon.com:8888
    check: "tcp-ping"
    url: btc.hiveon.com
    port: 8888
  - name: btc.hiveon.com:4444
    check: "tcp-ping"
    url: btc.hiveon.com
    port: 4444
  - name: btc.hiveon.com:20443
    check: "tcp-ping"
    url: btc.hiveon.com
    port: 20443
  - name: rvn.hiveon.com:8888
    check: "tcp-ping"
    url: rvn.hiveon.com
    port: 8888
  - name: rvn.hiveon.com:9999
    check: "tcp-ping"
    url: rvn.hiveon.com
    port: 9999
  - name: rvn.hiveon.com:7777
    check: "tcp-ping"
    url: rvn.hiveon.com
    port: 7777
  - name: etc.hiveon.com:8888
    check: "tcp-ping"
    url: etc.hiveon.com
    port: 8888
  - name: etc.hiveon.com:4444
    check: "tcp-ping"
    url: etc.hiveon.com
    port: 4444
  - name: etc.hiveon.com:20443
    check: "tcp-ping"
    url: etc.hiveon.com
    port: 20443
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  publish: true
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/the3line/upptime2/master/assets/HiveonLogo.svg
  name: Upptime
  introMessage: Status page for the Hiveon services
  navbar:
    - title: Status
      href: /status
    - title: hiveon.com
      href: https://hiveon.com

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

i18n:
  footer: Hiveon 
